[project]
name = "notify-to-line"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "line-bot-sdk>=3.16.3",
    "requests>=2.32.3",
]
